### ISSUE TITLE
Remove totally website

### ISSUE THREAD

**Issue by kosssi** [siteinspector/siteinspector#3]
When I'm adding a website, launch scan, remove website and add the same website, I can see the old report.

I think it's better to really remove all data ;)

**Comment by omohokcoj** [comment]
Removing data is slow and might be unnecessary because re-crawling a website will update the errors report entirely.
Currently, the 'remove' button works more like an 'archive' button which allows to restore the data afterward.

I think there might be some 'clear data' button that will run an async job to remove all DB entries related to some specific website. But usually, the entire report is worth of just a few megabytes so it can easily stay in the DB for a while :) 
Anyway, thanks for the feedback - that's definitely something we might consider adding in the future. @kosssi
